In [2]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix

In [3]:
names = ['Age', 'Sex', 'Chest Pain Type', 'trestbps', 'Chol', 'fbs', 'restecg', 'thalach', 'exang', 'olpeak', 'slope', 'ca', 'thal', 'Result']

In [5]:
df = pd.read_csv("/content/processed.cleveland.data", names=names)

In [6]:
df.head()

,Age,Sex,Chest Pain Type,trestbps,Chol,fbs,restecg,thalach,exang,olpeak,slope,ca,thal,Result
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [17]:
df

,Age,Sex,Chest Pain Type,trestbps,Chol,fbs,restecg,thalach,exang,olpeak,slope,ca,thal,Result
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [7]:
df.dtypes

Age                float64
Sex                float64
Chest Pain Type    float64
trestbps           float64
Chol               float64
fbs                float64
restecg            float64
thalach            float64
exang              float64
olpeak             float64
slope              float64
ca                  object
thal                object
Result               int64
dtype: object

In [16]:
df['ca'] = df['ca'].astype('float')

ValueError: could not convert string to float: '?'

In [19]:
df = df[df['ca'] != '?']

In [28]:
df['ca'] = df['ca'].astype('float')

/tmp/ipython-input-838633300.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ca'] = df['ca'].astype('float')

In [20]:
df

,Age,Sex,Chest Pain Type,trestbps,Chol,fbs,restecg,thalach,exang,olpeak,slope,ca,thal,Result
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1

In [23]:
df['thal'] = df['thal'].astype('float')

ValueError: could not convert string to float: '?'

In [24]:
df = df[df['thal'] != '?']

In [29]:
df['thal'] = df['thal'].astype('float')

/tmp/ipython-input-3537049178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['thal'] = df['thal'].astype('float')

In [25]:
df

,Age,Sex,Chest Pain Type,trestbps,Chol,fbs,restecg,thalach,exang,olpeak,slope,ca,thal,Result
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1

In [30]:
df.dtypes

Age                float64
Sex                float64
Chest Pain Type    float64
trestbps           float64
Chol               float64
fbs                float64
restecg            float64
thalach            float64
exang              float64
olpeak             float64
slope              float64
ca                 float64
thal               float64
Result               int64
dtype: object

In [31]:
df.isna().sum()

Age                0
Sex                0
Chest Pain Type    0
trestbps           0
Chol               0
fbs                0
restecg            0
thalach            0
exang              0
olpeak             0
slope              0
ca                 0
thal               0
Result             0
dtype: int64

In [75]:
#X = df[['Age', 'Sex', 'Chest Pain Type', 'trestbps', 'Chol', 'fbs', 'restecg', 'thalach', 'exang', 'olpeak', 'slope', 'ca', 'thal']]
X = df[['Age', 'Sex', 'Chest Pain Type', 'trestbps', 'Chol', 'fbs']]
y = df['Result']

In [76]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=45)

In [81]:
knn = KNeighborsClassifier(n_neighbors=7)

In [82]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [83]:
knn.score(X_test,y_test)

0.5166666666666667

In [84]:
knn.predict([[54.0,1.0,4.0,120.0,188.0,0.0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

array([0])