In [1]:
import pandas as pd

In [3]:
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [2, 4, 6, 8, 10]
}
df = pd.DataFrame(data)

In [4]:
df

   A  B   C
0  1  5   2
1  2  4   4
2  3  3   6
3  4  2   8
4  5  1  10

In [5]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [7]:
df['D'] = df['A'] * 2
df

   A  B   C   D
0  1  5   2   2
1  2  4   4   4
2  3  3   6   6
3  4  2   8   8
4  5  1  10  10

In [8]:
# Update a value
df.iloc[0,0] = 100
df

     A  B   C   D
0  100  5   2   2
1    2  4   4   4
2    3  3   6   6
3    4  2   8   8
4    5  1  10  10

In [9]:
df.iloc[0,3] = 20
df

     A  B   C   D
0  100  5   2  20
1    2  4   4   4
2    3  3   6   6
3    4  2   8   8
4    5  1  10  10

In [10]:
help(pd.DataFrame.iloc)

Help on property:

    Purely integer-location based indexing for selection by position.

    .. deprecated:: 2.2.0

       Returning a tuple from a callable is deprecated.

    ``.iloc[]`` is primarily integer position based (from ``0`` to
    ``length-1`` of the axis), but may also be used with a boolean
    array.

    Allowed inputs are:

    - An integer, e.g. ``5``.
    - A list or array of integers, e.g. ``[4, 3, 0]``.
    - A slice object with ints, e.g. ``1:7``.
    - A boolean array.
    - A ``callable`` function with one argument (the calling Series or
      DataFrame) and that returns valid output for indexing (one of the above).
      This is useful in method chains, when you don't have a reference to the
      calling object, but would like to base your selection on
      some value.
    - A tuple of row and column indexes. The tuple elements consist of one of the
      above inputs, e.g. ``(0, 1)``.

    ``.iloc`` will raise ``IndexError`` if a requested indexer is
    out-of-bounds, except *slice* indexers which allow out-of-bounds
    indexing (this conforms with python/numpy *slice* semantics).

    See more at :ref:`Selection by Position <indexing.integer>`.

    See Also
    --------
    DataFrame.iat : Fast integer location scalar accessor.
    DataFrame.loc : Purely label-location based indexer for selection by label.
    Series.iloc : Purely integer-location based indexing for
                   selection by position.

    Examples
    --------
    >>> mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
    ...           {'a': 100, 'b': 200, 'c': 300, 'd': 400},
    ...           {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]
    >>> df = pd.DataFrame(mydict)
    >>> df
          a     b     c     d
    0     1     2     3     4
    1   100   200   300   400
    2  1000  2000  3000  4000

    **Indexing just the rows**

    With a scalar integer.

    >>> type(df.iloc[0])
    <class 'pandas.core.series.Series'>
    >>> df.iloc[0]
    a    1
    b    2
    c    3
    d    4
    Name: 0, dtype: int64

    With a list of integers.

    >>> df.iloc[[0]]
       a  b  c  d
    0  1  2  3  4
    >>> type(df.iloc[[0]])
    <class 'pandas.core.frame.DataFrame'>

    >>> df.iloc[[0, 1]]
         a    b    c    d
    0    1    2    3    4
    1  100  200  300  400

    With a `slice` object.

    >>> df.iloc[:3]
          a     b     c     d
    0     1     2     3     4
    1   100   200   300   400
    2  1000  2000  3000  4000

    With a boolean mask the same length as the index.

    >>> df.iloc[[True, False, True]]
          a     b     c     d
    0     1     2     3     4
    2  1000  2000  3000  4000

    With a callable, useful in method chains. The `x` passed
    to the ``lambda`` is the DataFrame being sliced. This selects
    the rows whose index label even.

    >>> df.iloc[lambda x: x.index % 2 == 0]
          a     b     c     d
    0     1     2     3     4
    2  1000  2000  3000  4000

    **Indexing both axes**

    You can mix the indexer types for the index and columns. Use ``:`` to
    select the entire axis.

    With scalar integers.

    >>> df.iloc[0, 1]
    2

    With lists of integers.

    >>> df.iloc[[0, 2], [1, 3]]
          b     d
    0     2     4
    2  2000  4000

    With `slice` objects.

    >>> df.iloc[1:3, 0:3]
          a     b     c
    1   100   200   300
    2  1000  2000  3000

    With a boolean array whose length matches the columns.

    >>> df.iloc[:, [True, False, True, False]]
          a     c
    0     1     3
    1   100   300
    2  1000  3000

    With a callable function that expects the Series or DataFrame.

    >>> df.iloc[:, lambda df: [0, 2]]
          a     c
    0     1     3
    1   100   300
    2  1000  3000

In [11]:
df['newColumn'] = df['A'] + df['B']
df

     A  B   C   D  newColumn
0  100  5   2  20        105
1    2  4   4   4          6
2    3  3   6   6          6
3    4  2   8   8          6
4    5  1  10  10          6

In [12]:
# Drop column from a DataFrame
df = df.drop('newColumn', axis=1)
df

     A  B   C   D
0  100  5   2  20
1    2  4   4   4
2    3  3   6   6
3    4  2   8   8
4    5  1  10  10

In [13]:
# Drop row from a Dataframe
df = df.drop(0, axis=0)
df

   A  B   C   D
1  2  4   4   4
2  3  3   6   6
3  4  2   8   8
4  5  1  10  10

In [15]:
df['E'] = [10, 3, 2, 1]
df

   A  B   C   D   E
1  2  4   4   4  10
2  3  3   6   6   3
3  4  2   8   8   2
4  5  1  10  10   1

In [16]:
df = df.sort_values('E')
df

   A  B   C   D   E
4  5  1  10  10   1
3  4  2   8   8   2
2  3  3   6   6   3
1  2  4   4   4  10

In [17]:
df = df.sort_values('E', ascending=False)
df

   A  B   C   D   E
1  2  4   4   4  10
2  3  3   6   6   3
3  4  2   8   8   2
4  5  1  10  10   1

In [18]:
# Sum of a column
print(df['A'].sum())

14

In [19]:
print(df['A'].mean())

3.5

In [20]:
print(df.iloc[2].mean())

4.8

In [21]:
# Handling missing values
df1 = pd.DataFrame({
    'A': [1, 2, None],
    'B': [5, None, None],
    'C': [1, 2, 3]
})
df1

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [22]:
df1.to_excel("Data.xlsx")

In [23]:
# Finding missing values
df.isnull()

       A      B      C      D      E
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False

In [24]:
df1.isnull()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [25]:
# same as isnull
df.isna()

       A      B      C      D      E
1  False  False  False  False  False
2  False  False  False  False  False
3  False  False  False  False  False
4  False  False  False  False  False

In [26]:
df1.isna()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [27]:
df1.isna().sum()

A    1
B    2
C    0
dtype: int64

In [28]:
df1.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [29]:
df = df.dropna()
df

   A  B   C   D   E
1  2  4   4   4  10
2  3  3   6   6   3
3  4  2   8   8   2
4  5  1  10  10   1

In [30]:
df1 = df1.dropna()
df1

     A    B  C
0  1.0  5.0  1

In [31]:
df1 = pd.DataFrame({
    'A': [1, 2, None],
    'B': [5, None, None],
    'C': [1, 2, 3]
})
df1

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [34]:
df1 = df1.fillna(df1.mean())

In [36]:
df1

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

In [37]:
df2 = pd.DataFrame({
    'A': [1, 2, 'NaN'],
    'B': [5, 'Nan', None],
    'C': [1, 2, 3]
})
df2

     A     B  C
0    1     5  1
1    2   Nan  2
2  NaN  None  3

In [38]:
df3 = pd.DataFrame({
    'A': [1, 2, None],
    'B': [5, None, None],
    'C': [1, 2, 3]
})
df3

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [39]:
from os import name
df = pd.read_csv("/content/iris.data", names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'])
df

     sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [40]:
df.shape

(150, 5)

In [41]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
class            object
dtype: object

In [42]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64