In [ ]:
import pandas as pd

In [ ]:
column_names = ['mpg','cylinders','displacement','horsepower','weight','acceleration','model_year','origin','car_name']

In [ ]:
df = pd.read_csv('/content/auto-mpg.data',sep='\s+',names=column_names)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-750583838.py:1: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('/content/auto-mpg.data',sep='\s+',names=column_names)

In [ ]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [ ]:
df.shape

(398, 9)

In [ ]:
#Number of Rows
df.shape[0]

398

In [ ]:
#number Columns
df.shape[1]

9

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'car_name'],
      dtype='object')

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

ValueError: could not convert string to float: '?'

In [ ]:
df[df['horsepower'] == '?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
32,25.0,4,98.0,?,2046.0,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875.0,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835.0,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905.0,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320.0,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035.0,20.5,82,1,amc concord dl

In [ ]:
df = df[df['horsepower'] != '?']

In [ ]:
df.shape

(392, 9)

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
#Option 2 to convt object to float horsepower column
df = pd.read_csv('/content/auto-mpg.data',sep='\s+',names=column_names)

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-2782962931.py:2: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('/content/auto-mpg.data',sep='\s+',names=column_names)

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df[df['horsepower'] == '?']

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
32,25.0,4,98.0,?,2046.0,19.0,71,1,ford pinto
126,21.0,6,200.0,?,2875.0,17.0,74,1,ford maverick
330,40.9,4,85.0,?,1835.0,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,?,2905.0,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,?,2320.0,15.8,81,2,renault 18i
374,23.0,4,151.0,?,3035.0,20.5,82,1,amc concord dl

In [ ]:
df['horsepower'] = df['horsepower'].replace('?',0.0)

In [ ]:
df.iloc[[32,126,330,336,354,374],:]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
32,25.0,4,98.0,0.0,2046.0,19.0,71,1,ford pinto
126,21.0,6,200.0,0.0,2875.0,17.0,74,1,ford maverick
330,40.9,4,85.0,0.0,1835.0,17.3,80,2,renault lecar deluxe
336,23.6,4,140.0,0.0,2905.0,14.3,80,1,ford mustang cobra
354,34.5,4,100.0,0.0,2320.0,15.8,81,2,renault 18i
374,23.0,4,151.0,0.0,3035.0,20.5,82,1,amc concord dl

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

In [ ]:
df.shape

(398, 9)

In [ ]:
df = pd.read_csv('/content/auto-mpg.data',sep='\s+',names=column_names)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-750583838.py:1: SyntaxWarning: invalid escape sequence '\s'
  df = pd.read_csv('/content/auto-mpg.data',sep='\s+',names=column_names)

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df.to_csv('autompg_clean.csv')

In [ ]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [ ]:
df['horsepower'] = df['horsepower'].astype('float')

ValueError: could not convert string to float: '?'

In [ ]:
mean_mpg = df['mpg'].mean()

In [ ]:
mean_mpg

np.float64(23.514572864321607)

In [ ]:
mean_horse = df['horsepower'].astype('float').mean()

In [ ]:
mean_horse

np.float64(104.46938775510205)

In [ ]:
df['horsepower'] = df['horsepower'].replace('NaN',mean_horse)

In [ ]:
df.iloc[[32,354],:]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
32,25.0,4,98.0,104.469388,2046.0,19.0,71,1,ford pinto
354,34.5,4,100.0,104.469388,2320.0,15.8,81,2,renault 18i

In [ ]:
df.shape

(398, 9)