In [16]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.utils import to_categorical

In [4]:
text = 'abcdefghi'
chars = sorted(list(set(text)))
chars

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [5]:
char_to_index = {c:i for i,c in enumerate(chars)}
char_to_index

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8}

In [39]:
index_to_char = {i:c for i,c in enumerate(chars)}
index_to_char

{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i'}

In [6]:
sequence_length = 1
input_sequence = []
target_sequence = []

for i in range(len(text) - sequence_length):
  input_sequence.append(text[i:i + sequence_length])
  target_sequence.append(text[i + sequence_length])

In [7]:
input_sequence

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [8]:
target_sequence

['b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']

In [29]:
X = np.array([[char_to_index[char] for char in seq] for seq in input_sequence])
y = np.array([char_to_index[char] for char in target_sequence])

In [31]:
X

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [30]:
y = to_categorical(y, num_classes=len(chars))

In [32]:
y

array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [33]:
model = Sequential()
model.add(Embedding(len(chars), 10, input_length=sequence_length))
model.add(LSTM(50, return_sequences=False))
model.add(Dense(len(chars), activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [34]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [35]:
model.fit(X,y, epochs=200)

Epoch 1/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.0000e+00 - loss: 2.1974
Epoch 2/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.1250 - loss: 2.1964
Epoch 3/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.2500 - loss: 2.1955
Epoch 4/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2500 - loss: 2.1946
Epoch 5/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.2500 - loss: 2.1936
Epoch 6/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.2500 - loss: 2.1927
Epoch 7/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.3750 - loss: 2.1917
Epoch 8/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.3750 - loss: 2.1908
Epoch 9/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.3750 - loss: 2.1898
Epoch 10/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.3750 - loss: 2.1888
Epoch 11/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 2.1878
Epoch 12/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.2500 - loss: 2.1868
Epoch 13/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.2500 - loss: 2.1858
Epoch 14/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.2500 - loss: 2.1848
Epoch 15/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.2500 - loss: 2.1837
Epoch 16/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.2500 - loss: 2.1826
Epoch 17/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3750 - loss: 2.1815
Epoch 18/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3750 - loss: 2.1804
Epoch 19/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.3750 - loss: 2.1793
Epoch 20/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.3750 - loss: 2.1781
Epoch 21/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3750 - loss: 2.1769
Epoch 22/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.3750 - loss: 2.1756
Epoch 23/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3750 - loss: 2.1744
Epoch 24/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 0.3750 - loss: 2.1731
Epoch 25/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3750 - loss: 2.1717
Epoch 26/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3750 - loss: 2.1703
Epoch 27/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3750 - loss: 2.1689
Epoch 28/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3750 - loss: 2.1675
Epoch 29/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3750 - loss: 2.1660
Epoch 30/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.3750 - loss: 2.1645
Epoch 31/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3750 - loss: 2.1629
Epoch 32/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3750 - loss: 2.1613
Epoch 33/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3750 - loss: 2.1596
Epoch 34/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.3750 - loss: 2.1579
Epoch 35/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3750 - loss: 2.1561
Epoch 36/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.3750 - loss: 2.1542
Epoch 37/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3750 - loss: 2.1524
Epoch 38/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.3750 - loss: 2.1504
Epoch 39/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3750 - loss: 2.1484
Epoch 40/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 2.1464
Epoch 41/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 2.1442
Epoch 42/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 2.1421
Epoch 43/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 2.1398
Epoch 44/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 2.1375
Epoch 45/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 2.1351
Epoch 46/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 2.1326
Epoch 47/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6250 - loss: 2.1301
Epoch 48/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6250 - loss: 2.1275
Epoch 49/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6250 - loss: 2.1248
Epoch 50/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6250 - loss: 2.1220
Epoch 51/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6250 - loss: 2.1192
Epoch 52/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6250 - loss: 2.1162
Epoch 53/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6250 - loss: 2.1132
Epoch 54/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 2.1101
Epoch 55/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 2.1068
Epoch 56/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 2.1035
Epoch 57/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 2.1001
Epoch 58/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 2.0966
Epoch 59/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 2.0930
Epoch 60/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 2.0893
Epoch 61/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 2.0855
Epoch 62/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6250 - loss: 2.0815
Epoch 63/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6250 - loss: 2.0775
Epoch 64/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6250 - loss: 2.0733
Epoch 65/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6250 - loss: 2.0690
Epoch 66/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 2.0646
Epoch 67/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 2.0601
Epoch 68/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 2.0554
Epoch 69/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 2.0506
Epoch 70/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 2.0457
Epoch 71/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 2.0406
Epoch 72/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 2.0354
Epoch 73/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 2.0301
Epoch 74/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 2.0246
Epoch 75/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 2.0190
Epoch 76/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 2.0132
Epoch 77/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 2.0073
Epoch 78/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 2.0013
Epoch 79/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 1.9950
Epoch 80/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.9887
Epoch 81/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.9821
Epoch 82/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7500 - loss: 1.9755
Epoch 83/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.9686
Epoch 84/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 1.9616
Epoch 85/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.9544
Epoch 86/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.9471
Epoch 87/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7500 - loss: 1.9396
Epoch 88/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.9319
Epoch 89/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 1.9240
Epoch 90/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 1.9160
Epoch 91/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.9079
Epoch 92/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.8995
Epoch 93/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 1.8910
Epoch 94/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.7500 - loss: 1.8823
Epoch 95/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.8734
Epoch 96/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 1.8644
Epoch 97/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.8552
Epoch 98/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7500 - loss: 1.8458
Epoch 99/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7500 - loss: 1.8363
Epoch 100/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7500 - loss: 1.8266
Epoch 101/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 1.8168
Epoch 102/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.8068
Epoch 103/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.7966
Epoch 104/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.7863
Epoch 105/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.7758
Epoch 106/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.7500 - loss: 1.7651
Epoch 107/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7500 - loss: 1.7543
Epoch 108/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 1.7434
Epoch 109/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.7324
Epoch 110/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.7211
Epoch 111/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.7098
Epoch 112/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 1.6983
Epoch 113/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.7500 - loss: 1.6867
Epoch 114/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.6750
Epoch 115/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.6632
Epoch 116/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.6512
Epoch 117/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.6391
Epoch 118/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8750 - loss: 1.6270
Epoch 119/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8750 - loss: 1.6147
Epoch 120/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.6023
Epoch 121/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8750 - loss: 1.5899
Epoch 122/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.5773
Epoch 123/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.5647
Epoch 124/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8750 - loss: 1.5520
Epoch 125/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.5392
Epoch 126/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.5264
Epoch 127/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.5135
Epoch 128/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.5005
Epoch 129/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.4875
Epoch 130/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.4744
Epoch 131/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8750 - loss: 1.4613
Epoch 132/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.4481
Epoch 133/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.4349
Epoch 134/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8750 - loss: 1.4217
Epoch 135/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8750 - loss: 1.4084
Epoch 136/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.3951
Epoch 137/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.3818
Epoch 138/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.3684
Epoch 139/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.3550
Epoch 140/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8750 - loss: 1.3417
Epoch 141/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8750 - loss: 1.3282
Epoch 142/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.3148
Epoch 143/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.3014
Epoch 144/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8750 - loss: 1.2879
Epoch 145/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8750 - loss: 1.2745
Epoch 146/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.2610
Epoch 147/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.2476
Epoch 148/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.2341
Epoch 149/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8750 - loss: 1.2207
Epoch 150/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.2073
Epoch 151/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.1938
Epoch 152/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8750 - loss: 1.1804
Epoch 153/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8750 - loss: 1.1670
Epoch 154/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8750 - loss: 1.1536
Epoch 155/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.1402
Epoch 156/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.1269
Epoch 157/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.1135
Epoch 158/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 1.1002
Epoch 159/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.0869
Epoch 160/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8750 - loss: 1.0737
Epoch 161/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.0605
Epoch 162/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.0473
Epoch 163/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.0342
Epoch 164/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8750 - loss: 1.0211
Epoch 165/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.8750 - loss: 1.0080
Epoch 166/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8750 - loss: 0.9950
Epoch 167/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8750 - loss: 0.9821
Epoch 168/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8750 - loss: 0.9692
Epoch 169/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.9563
Epoch 170/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.9435
Epoch 171/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.9308
Epoch 172/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.9182
Epoch 173/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.9056
Epoch 174/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.8931
Epoch 175/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.8807
Epoch 176/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.8684
Epoch 177/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.8562
Epoch 178/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.8440
Epoch 179/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.8320
Epoch 180/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.8200
Epoch 181/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.8081
Epoch 182/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.7964
Epoch 183/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.7847
Epoch 184/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.7732
Epoch 185/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.7618
Epoch 186/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.7504
Epoch 187/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.7392
Epoch 188/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.7282
Epoch 189/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.7172
Epoch 190/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.7064
Epoch 191/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.6957
Epoch 192/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.6851
Epoch 193/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.6746
Epoch 194/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.6643
Epoch 195/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.6541
Epoch 196/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.6441
Epoch 197/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.6341
Epoch 198/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.6243
Epoch 199/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 1.0000 - loss: 0.6147
Epoch 200/200
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.6052

In [40]:
def predict_next(model, char):
  x = np.array([char_to_index[char]])
  pred = model.predict(x, verbose=0)[0]
  pred_char = index_to_char[np.argmax(pred)]
  return pred_char

In [41]:
input_char = 'h'
predicted_char = predict_next(model, input_char)
print(f"Given the character : '{input_char}', the predicted character is '{predicted_char}'")

Given the character : 'h', the predicted character is 'i'

In [43]:
input_char = 'b'
predicted_char = predict_next(model, input_char)
print(f"Given the character : '{input_char}', the predicted character is '{predicted_char}'")

Given the character : 'b', the predicted character is 'c'

In [45]:
input_char = 'd'
predicted_char = predict_next(model, input_char)
print(f"Given the character : '{input_char}', the predicted character is '{predicted_char}'")

Given the character : 'd', the predicted character is 'e'

In [46]:
import pandas as pd
df = pd.read_csv('spam.csv', encoding='ISO-8859-1')
df.head()

,type,text,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [48]:
df = df[['type', 'text']]
df.head()

   type                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [50]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [51]:
df['type'] = df['type'].map({'ham':0, 'spam':1})
df.head()

/tmp/ipython-input-1633798012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['type'] = df['type'].map({'ham':0, 'spam':1})

   type                                               text
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...
2     1  Free entry in 2 a wkly comp to win FA Cup fina...
3     0  U dun say so early hor... U c already then say...
4     0  Nah I don't think he goes to usf, he lives aro...

In [52]:
tokeniser = Tokenizer(num_words=5000, oov_token='<OOV>')
tokeniser.fit_on_texts(df['text'])
sequences = tokeniser.texts_to_sequences(df['text'])

In [53]:
max_sequence_length = 100
X = pad_sequences(sequences, maxlen=max_sequence_length)
y = df['type'].values

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
model = Sequential()
model.add(Embedding(input_dim=5000, output_dim=128, input_length=max_sequence_length))
model.add(LSTM(128, return_sequences=True))
model.add(LSTM(64))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [57]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [58]:
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100)

Epoch 1/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.8976 - loss: 0.2355 - val_accuracy: 0.9794 - val_loss: 0.0743
Epoch 2/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9916 - loss: 0.0285 - val_accuracy: 0.9839 - val_loss: 0.0566
Epoch 3/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 0.9975 - loss: 0.0116 - val_accuracy: 0.9821 - val_loss: 0.0710
Epoch 4/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9991 - loss: 0.0041 - val_accuracy: 0.9857 - val_loss: 0.0585
Epoch 5/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.9977 - loss: 0.0047 - val_accuracy: 0.9830 - val_loss: 0.0655
Epoch 6/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.8011e-04 - val_accuracy: 0.9857 - val_loss: 0.0640
Epoch 7/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.9995 - loss: 7.4711e-04 - val_accuracy: 0.9830 - val_loss: 0.0938
Epoch 8/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 8.9187e-05 - val_accuracy: 0.9830 - val_loss: 0.0966
Epoch 9/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 5.9473e-05 - val_accuracy: 0.9830 - val_loss: 0.0998
Epoch 10/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 1.0000 - loss: 4.5449e-05 - val_accuracy: 0.9830 - val_loss: 0.1021
Epoch 11/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 1.0000 - loss: 3.8972e-05 - val_accuracy: 0.9830 - val_loss: 0.1047
Epoch 12/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 3.4483e-05 - val_accuracy: 0.9830 - val_loss: 0.1070
Epoch 13/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.8078e-05 - val_accuracy: 0.9821 - val_loss: 0.1090
Epoch 14/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.3437e-05 - val_accuracy: 0.9821 - val_loss: 0.1108
Epoch 15/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.0868e-05 - val_accuracy: 0.9821 - val_loss: 0.1125
Epoch 16/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 1.0000 - loss: 1.9335e-05 - val_accuracy: 0.9821 - val_loss: 0.1147
Epoch 17/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 1.0000 - loss: 1.5541e-05 - val_accuracy: 0.9821 - val_loss: 0.1149
Epoch 18/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.3200e-05 - val_accuracy: 0.9821 - val_loss: 0.1167
Epoch 19/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 1.0000 - loss: 1.2618e-05 - val_accuracy: 0.9821 - val_loss: 0.1184
Epoch 20/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.1108e-05 - val_accuracy: 0.9821 - val_loss: 0.1200
Epoch 21/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.0020e-05 - val_accuracy: 0.9821 - val_loss: 0.1214
Epoch 22/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 1.0000 - loss: 8.5444e-06 - val_accuracy: 0.9821 - val_loss: 0.1229
Epoch 23/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 1.0000 - loss: 7.6961e-06 - val_accuracy: 0.9821 - val_loss: 0.1240
Epoch 24/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 8.8095e-06 - val_accuracy: 0.9821 - val_loss: 0.1253
Epoch 25/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 6.9912e-06 - val_accuracy: 0.9821 - val_loss: 0.1265
Epoch 26/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 6.5543e-06 - val_accuracy: 0.9821 - val_loss: 0.1275
Epoch 27/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 5.7580e-06 - val_accuracy: 0.9821 - val_loss: 0.1285
Epoch 28/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 4.9524e-06 - val_accuracy: 0.9821 - val_loss: 0.1294
Epoch 29/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 4.2122e-06 - val_accuracy: 0.9821 - val_loss: 0.1303
Epoch 30/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 4.6434e-06 - val_accuracy: 0.9821 - val_loss: 0.1310
Epoch 31/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 3.6250e-06 - val_accuracy: 0.9821 - val_loss: 0.1319
Epoch 32/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 3.7276e-06 - val_accuracy: 0.9821 - val_loss: 0.1326
Epoch 33/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 3.1156e-06 - val_accuracy: 0.9821 - val_loss: 0.1334
Epoch 34/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.8585e-06 - val_accuracy: 0.9821 - val_loss: 0.1339
Epoch 35/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 1.0000 - loss: 2.8546e-06 - val_accuracy: 0.9821 - val_loss: 0.1347
Epoch 36/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 2.6560e-06 - val_accuracy: 0.9821 - val_loss: 0.1353
Epoch 37/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.4095e-06 - val_accuracy: 0.9821 - val_loss: 0.1362
Epoch 38/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 2.1059e-06 - val_accuracy: 0.9821 - val_loss: 0.1368
Epoch 39/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.9052e-06 - val_accuracy: 0.9821 - val_loss: 0.1376
Epoch 40/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.9155e-06 - val_accuracy: 0.9821 - val_loss: 0.1376
Epoch 41/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.7904e-06 - val_accuracy: 0.9821 - val_loss: 0.1383
Epoch 42/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 1.0000 - loss: 1.6128e-06 - val_accuracy: 0.9821 - val_loss: 0.1389
Epoch 43/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 1.0000 - loss: 1.6654e-06 - val_accuracy: 0.9821 - val_loss: 0.1394
Epoch 44/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 1.0000 - loss: 1.4266e-06 - val_accuracy: 0.9821 - val_loss: 0.1400
Epoch 45/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 1.0000 - loss: 1.2763e-06 - val_accuracy: 0.9821 - val_loss: 0.1405
Epoch 46/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 1.0000 - loss: 1.1554e-06 - val_accuracy: 0.9821 - val_loss: 0.1411
Epoch 47/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 31ms/step - accuracy: 1.0000 - loss: 1.0999e-06 - val_accuracy: 0.9821 - val_loss: 0.1415
Epoch 48/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 1.0000 - loss: 1.1235e-06 - val_accuracy: 0.9830 - val_loss: 0.1421
Epoch 49/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 1.0000 - loss: 1.1206e-06 - val_accuracy: 0.9830 - val_loss: 0.1428
Epoch 50/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 1.0000 - loss: 9.4496e-07 - val_accuracy: 0.9830 - val_loss: 0.1433
Epoch 51/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 5s 19ms/step - accuracy: 1.0000 - loss: 9.2539e-07 - val_accuracy: 0.9830 - val_loss: 0.1442
Epoch 52/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 7.7743e-07 - val_accuracy: 0.9830 - val_loss: 0.1445
Epoch 53/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 1.0000 - loss: 7.4283e-07 - val_accuracy: 0.9830 - val_loss: 0.1450
Epoch 54/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - accuracy: 1.0000 - loss: 6.7568e-07 - val_accuracy: 0.9830 - val_loss: 0.1457
Epoch 55/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - accuracy: 1.0000 - loss: 6.3943e-07 - val_accuracy: 0.9839 - val_loss: 0.1463
Epoch 56/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 1.0000 - loss: 6.1883e-07 - val_accuracy: 0.9839 - val_loss: 0.1470
Epoch 57/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - accuracy: 1.0000 - loss: 6.4879e-07 - val_accuracy: 0.9839 - val_loss: 0.1478
Epoch 58/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 5.0662e-07 - val_accuracy: 0.9839 - val_loss: 0.1485
Epoch 59/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 1.0000 - loss: 5.0281e-07 - val_accuracy: 0.9839 - val_loss: 0.1493
Epoch 60/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 1.0000 - loss: 4.3185e-07 - val_accuracy: 0.9839 - val_loss: 0.1501
Epoch 61/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 5s 34ms/step - accuracy: 1.0000 - loss: 4.2943e-07 - val_accuracy: 0.9839 - val_loss: 0.1508
Epoch 62/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 1.0000 - loss: 3.8482e-07 - val_accuracy: 0.9839 - val_loss: 0.1517
Epoch 63/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 1.0000 - loss: 3.5033e-07 - val_accuracy: 0.9839 - val_loss: 0.1524
Epoch 64/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 3.5253e-07 - val_accuracy: 0.9839 - val_loss: 0.1530
Epoch 65/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 1.0000 - loss: 3.1794e-07 - val_accuracy: 0.9839 - val_loss: 0.1542
Epoch 66/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 3.1432e-07 - val_accuracy: 0.9839 - val_loss: 0.1545
Epoch 67/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 2.8244e-07 - val_accuracy: 0.9839 - val_loss: 0.1553
Epoch 68/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 1.0000 - loss: 2.5424e-07 - val_accuracy: 0.9839 - val_loss: 0.1559
Epoch 69/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 1.0000 - loss: 2.5138e-07 - val_accuracy: 0.9839 - val_loss: 0.1568
Epoch 70/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 6s 41ms/step - accuracy: 1.0000 - loss: 2.2362e-07 - val_accuracy: 0.9839 - val_loss: 0.1574
Epoch 71/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 1.0000 - loss: 2.0473e-07 - val_accuracy: 0.9839 - val_loss: 0.1583
Epoch 72/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 1.0000 - loss: 1.9660e-07 - val_accuracy: 0.9839 - val_loss: 0.1587
Epoch 73/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 1.0000 - loss: 1.8324e-07 - val_accuracy: 0.9839 - val_loss: 0.1592
Epoch 74/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 1.0000 - loss: 1.7508e-07 - val_accuracy: 0.9839 - val_loss: 0.1598
Epoch 75/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 1.0000 - loss: 1.6372e-07 - val_accuracy: 0.9839 - val_loss: 0.1603
Epoch 76/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 7s 29ms/step - accuracy: 1.0000 - loss: 1.5265e-07 - val_accuracy: 0.9839 - val_loss: 0.1609
Epoch 77/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 1.3636e-07 - val_accuracy: 0.9839 - val_loss: 0.1613
Epoch 78/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.4329e-07 - val_accuracy: 0.9848 - val_loss: 0.1619
Epoch 79/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 1.2067e-07 - val_accuracy: 0.9848 - val_loss: 0.1623
Epoch 80/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 1.0000 - loss: 1.0976e-07 - val_accuracy: 0.9848 - val_loss: 0.1629
Epoch 81/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 1.0000 - loss: 1.0604e-07 - val_accuracy: 0.9848 - val_loss: 0.1630
Epoch 82/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 1.0000 - loss: 1.0121e-07 - val_accuracy: 0.9848 - val_loss: 0.1633
Epoch 83/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 1.0000 - loss: 8.8264e-08 - val_accuracy: 0.9848 - val_loss: 0.1642
Epoch 84/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 1.0000 - loss: 9.3585e-08 - val_accuracy: 0.9848 - val_loss: 0.1637
Epoch 85/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 1.0000 - loss: 8.0538e-08 - val_accuracy: 0.9848 - val_loss: 0.1641
Epoch 86/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 7.7550e-08 - val_accuracy: 0.9848 - val_loss: 0.1642
Epoch 87/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 1.0000 - loss: 7.3471e-08 - val_accuracy: 0.9848 - val_loss: 0.1647
Epoch 88/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - accuracy: 1.0000 - loss: 6.7048e-08 - val_accuracy: 0.9848 - val_loss: 0.1651
Epoch 89/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 6.2794e-08 - val_accuracy: 0.9848 - val_loss: 0.1656
Epoch 90/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 28ms/step - accuracy: 1.0000 - loss: 5.8797e-08 - val_accuracy: 0.9848 - val_loss: 0.1661
Epoch 91/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - accuracy: 1.0000 - loss: 5.6098e-08 - val_accuracy: 0.9857 - val_loss: 0.1671
Epoch 92/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 5.4138e-08 - val_accuracy: 0.9857 - val_loss: 0.1676
Epoch 93/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 1.0000 - loss: 5.4025e-08 - val_accuracy: 0.9857 - val_loss: 0.1683
Epoch 94/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - accuracy: 1.0000 - loss: 4.6551e-08 - val_accuracy: 0.9857 - val_loss: 0.1690
Epoch 95/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - accuracy: 1.0000 - loss: 4.3702e-08 - val_accuracy: 0.9848 - val_loss: 0.1699
Epoch 96/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 3.9670e-08 - val_accuracy: 0.9848 - val_loss: 0.1707
Epoch 97/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 4.1372e-08 - val_accuracy: 0.9848 - val_loss: 0.1716
Epoch 98/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - accuracy: 1.0000 - loss: 3.4570e-08 - val_accuracy: 0.9848 - val_loss: 0.1724
Epoch 99/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 1.0000 - loss: 3.1939e-08 - val_accuracy: 0.9848 - val_loss: 0.1733
Epoch 100/100
140/140 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 1.0000 - loss: 3.1382e-08 - val_accuracy: 0.9848 - val_loss: 0.1742

In [59]:
def predict_message(msg: str):
  seq = tokeniser.texts_to_sequences([msg])
  pad = pad_sequences(seq, maxlen=max_sequence_length, padding='post', truncating='post')
  prob = model.predict(pad)[0][0]
  label = "spam" if prob > 0.5 else "ham"
  return label, float(prob)

In [62]:
examples = [
    "Congratulations! You've won a $1000 free vacation! Call Now",
    "Hi, are we still meeting at 5 pm today?"
]

In [63]:
for m in examples:
  label, p = predict_message(m)
  print(f"Message: {m}\nPredicted: {label} (spam probability={p: 3f})\n")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Message: Congratulations! You've won a $1000 free vacation! Call Now
Predicted: ham (spam probability= 0.000000)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Message: Hi, are we still meeting at 5 pm today?
Predicted: ham (spam probability= 0.000000)